
name: digital-wallet
services:
  backend:
    image: digital-wallet-backend:latest
    build:
      context: ../backend
    container_name: digital_wallet_backend
    restart: always
    ports:
      - "3006:3006"
      - "8080:3006"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-digital_wallet}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-admin123}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - TOKEN_SECRET=${TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: digital-wallet-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: digital_wallet_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - SPRING_BOOT_URL=${SPRING_BOOT_INTERNAL_URL:-http://backend:3006/api/v1}
      - SESSION_SECRET=${SESSION_SECRET:-digital_wallet_secret_session_key_32_characters_minimum_length_required}
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started

  pg_admin:
    image: dpage/pgadmin4
    container_name: digital_wallet_pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@digitalwallet.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: digital_wallet_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-digital_wallet}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-digital_wallet}"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: digital_wallet_redis
    restart: always
    depends_on:
      - postgres
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: