spring:
  mvc:
    servlet:
      path: "/api/v1"
  application:
    name: digital-wallet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digital_wallet}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
server:
  port: 3006