spring:
  mvc:
    servlet:
      path: "/api/v1"
  application:
    name: digital-wallet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digital_wallet}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
jwt:
  secret: ${TOKEN_SECRET:secret12345678901234567890123456789012}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:604800000}
  cookie:
    secure: ${JWT_COOKIE_SECURE:false}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 3006